import json

def code(src):
    return {"cell_type":"code","metadata":{},"execution_count":None,"outputs":[],"source":src.splitlines(keepends=True)}
def md(src):
    return {"cell_type":"markdown","metadata":{},"source":src.splitlines(keepends=True)}

cells=[]
cells.append(md("# Qwen3-14B abliterated + llama-cpp-python (GPU, thinking ON)\nOllama on Colab doesn't use GPU. This uses llama-cpp-python prebuilt CUDA wheel (GPU) + chatml format + thinking ON = fast + good quality.\nRun all cells top to bottom."))

cells.append(code("!nvidia-smi || echo 'no GPU'"))

cells.append(code(
"!pip -q install llama-cpp-python==0.3.34 --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu124\n"
"!pip -q install fastapi uvicorn huggingface_hub\n"
"import llama_cpp; print('llama-cpp-python', llama_cpp.__version__)"
))

cells.append(code(
"import os\n"
"from huggingface_hub import hf_hub_download\n"
"MODEL_DIR='/content/models'; os.makedirs(MODEL_DIR, exist_ok=True)\n"
"MODEL_FILE='huihui-ai_Qwen3-14B-abliterated-Q4_K_M.gguf'\n"
"local_path=os.path.join(MODEL_DIR, MODEL_FILE)\n"
"if os.path.exists(local_path) and os.path.getsize(local_path)==9001749568:\n"
"    print('model complete')\n"
"else:\n"
"    print('downloading (~9GB)...')\n"
"    hf_hub_download(repo_id='bartowski/huihui-ai_Qwen3-14B-abliterated-GGUF', filename=MODEL_FILE, local_dir=MODEL_DIR)\n"
"print('path:', local_path)"
))

S = (
"# Server: chatml + thinking ON + GPU + tools + tunnel\n"
"import subprocess, os, json, threading, time, urllib.request\n"
"from llama_cpp import Llama\n"
"from fastapi import FastAPI, Request\n"
"from fastapi.responses import FileResponse, StreamingResponse\n"
"from fastapi.middleware.cors import CORSMiddleware\n"
"import uvicorn\n"
"\n"
"# chat.html from repo\n"
"subprocess.run(['wget','-q','https://raw.githubusercontent.com/minam67889-bit/llm-uncensored-toolkit/main/chat.html','-O','/content/chat.html'])\n"
"\n"
"print('loading model on GPU...')\n"
"llm = Llama(model_path=local_path, n_gpu_layers=-1, n_ctx=8192, chat_format='chatml', verbose=False)\n"
"print('model loaded')\n"
"\n"
"app = FastAPI()\n"
"app.add_middleware(CORSMiddleware, allow_origins=['*'], allow_methods=['*'], allow_headers=['*'])\n"
"\n"
"@app.get('/')\n"
"async def _i(): return FileResponse('/content/chat.html', media_type='text/html', headers={'Cache-Control':'no-store'})\n"
"@app.get('/health')\n"
"def _h(): return {'status':'ok'}\n"
"@app.get('/v1/models')\n"
"def _m(): return {'object':'list','data':[{'id':'qwen3-14b-abliterated','object':'model'}]}\n"
"\n"
"@app.post('/v1/chat/completions')\n"
"async def _c(req: Request):\n"
"    body = await req.json()\n"
"    msgs = body.get('messages', [])\n"
"    p = dict(max_tokens=int(body.get('max_tokens',4096)), temperature=float(body.get('temperature',0.3)), top_p=0.95)\n"
"    if body.get('stream'):\n"
"        def gen():\n"
"            try:\n"
"                for ch in llm.create_chat_completion(messages=msgs, stream=True, **p):\n"
"                    yield 'data: ' + json.dumps(ch) + chr(10) + chr(10)\n"
"            except Exception as e:\n"
"                print('ERR:', repr(e), flush=True)\n"
"                yield 'data: ' + json.dumps({'choices':[{'index':0,'delta':{'content':'[ERR '+str(e)[:200]+']'}}]}) + chr(10) + chr(10)\n"
"            yield 'data: [DONE]' + chr(10) + chr(10)\n"
"        return StreamingResponse(gen(), media_type='text/event-stream', headers={'Cache-Control':'no-store'})\n"
"    try:\n"
"        return llm.create_chat_completion(messages=msgs, **p)\n"
"    except Exception as e:\n"
"        return {'error':{'message':str(e)}}\n"
"\n"
"# tools\n"
"AWS='/content/workspace'; os.makedirs(AWS, exist_ok=True)\n"
"def _r(path):\n"
"    p=os.path.realpath(os.path.join(AWS,path))\n"
"    if not(p==AWS or p.startswith(AWS+os.sep)): raise PermissionError('outside')\n"
"    return p\n"
"@app.post('/v1/tools/bash')\n"
"async def _b(req):\n"
"    cmd=(await req.json()).get('cmd','')\n"
"    try:\n"
"        r=subprocess.run(cmd,shell=True,cwd=AWS,capture_output=True,text=True,timeout=600)\n"
"        out=(r.stdout or '')+((chr(10)+r.stderr) if r.stderr else '')\n"
"        return {'result':out.strip()[:12000]+((chr(10)+'[exit '+str(r.returncode)+']') if r.returncode else '')}\n"
"    except subprocess.TimeoutExpired: return {'result':'[timeout]'}\n"
"    except Exception as e: return {'result':'[error: '+str(e)+']'}\n"
"@app.post('/v1/tools/read_file')\n"
"async def _rf(req):\n"
"    try: return {'result':open(_r((await req.json()).get('path','')),encoding='utf-8',errors='replace').read()[:12000]}\n"
"    except Exception as e: return {'result':'[error: '+str(e)+']'}\n"
"@app.post('/v1/tools/write_file')\n"
"async def _wf(req):\n"
"    try:\n"
"        b=await req.json(); p=_r(b.get('path','')); os.makedirs(os.path.dirname(p),exist_ok=True)\n"
"        open(p,'w',encoding='utf-8').write(b.get('content','')); return {'result':'[written] '+b.get('path','')}\n"
"    except Exception as e: return {'result':'[error: '+str(e)+']'}\n"
"@app.post('/v1/tools/list_dir')\n"
"async def _ls(req):\n"
"    try:\n"
"        b=await req.json(); root=_r(b.get('path','.')); rows=[]\n"
"        for r2,ds,fs in os.walk(root):\n"
"            ds[:]=[d for d in ds if d not in('.git','node_modules','__pycache__')]\n"
"            rel=os.path.relpath(r2,AWS)\n"
"            for f in fs: rows.append(os.path.join(rel,f) if rel!='.' else f)\n"
"            if not b.get('recursive'): ds[:]=[]\n"
"        return {'result':chr(10).join(sorted(rows)[:300]) or '[empty]'}\n"
"    except Exception as e: return {'result':'[error: '+str(e)+']'}\n"
"@app.post('/v1/upload')\n"
"async def _up(req):\n"
"    import base64\n"
"    try:\n"
"        b=await req.json(); fn=''.join(c for c in os.path.basename(b.get('filename','u.bin')) if c.isalnum() or c in '._-')\n"
"        p=_r(fn); os.makedirs(os.path.dirname(p),exist_ok=True); open(p,'wb').write(base64.b64decode(b.get('content','')))\n"
"        return {'result':'[uploaded] '+fn,'path':p}\n"
"    except Exception as e: return {'result':'[error: '+str(e)+']','path':''}\n"
"\n"
"# start server\n"
"cfg=uvicorn.Config(app, host='0.0.0.0', port=8000, log_level='warning')\n"
"uvS=uvicorn.Server(cfg)\n"
"threading.Thread(target=uvS.run, daemon=True).start()\n"
"for _ in range(60):\n"
"    try: urllib.request.urlopen('http://localhost:8000/health',timeout=3); break\n"
"    except Exception: time.sleep(1)\n"
"\n"
"# tunnel\n"
"subprocess.run(['wget','-q','https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64','-O','/usr/local/bin/cloudflared'])\n"
"subprocess.run(['chmod','+x','/usr/local/bin/cloudflared'])\n"
"cf=subprocess.Popen(['cloudflared','tunnel','--url','http://localhost:8000'],stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True,bufsize=1)\n"
"TUNNEL_URL=None\n"
"def _rd():\n"
"    global TUNNEL_URL\n"
"    for line in cf.stdout:\n"
"        if 'trycloudflare.com' in line:\n"
"            parts=line.split()\n"
"            for p in parts:\n"
"                if p.startswith('https://') and 'trycloudflare' in p:\n"
"                    TUNNEL_URL=p.strip(); break\n"
"            if TUNNEL_URL: break\n"
"threading.Thread(target=_rd,daemon=True).start()\n"
"for _ in range(90):\n"
"    if TUNNEL_URL: break\n"
"    time.sleep(1)\n"
"print('='*52)\n"
"print('READY! Open:')\n"
"print('   ',TUNNEL_URL or '(failed)')\n"
"print('='*52)\n"
)
cells.append(code(S))

cells.append(md("Open the trycloudflare URL. Model auto-selected. Thinking is ON (like HuggingFace). chat.html strips <think> for clean display.\n\n14B fits T4 fully (~15-30 tok/s). No offload, no 524."))

cells.append(code(
"try:\n"
"    cf.terminate(); uvS.should_exit=True\n"
"    print('stopped')\n"
"except: pass"
))

nb={"nbformat":4,"nbformat_minor":5,"metadata":{"accelerator":"GPU","colab":{"provenance":[],"gpuType":"T4","toc_visible":True},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":cells}
open('/home/user/colab_setup.ipynb','w',encoding='utf-8').write(json.dumps(nb,ensure_ascii=False,indent=1))
print('cells:',len(cells))
